"""Shared limits that affect device collection and summary calculations."""

MAX_SUMMARY_ITEMS = 500
MAX_RETAINED_COLLECTION_BYTES = 100 * 1024 * 1024
MAX_UPLOAD_BYTES = MAX_RETAINED_COLLECTION_BYTES
MAX_SUMMARY_TEXT_BYTES = MAX_RETAINED_COLLECTION_BYTES
MAX_RESPONSE_OUTPUT_CHARS = 200_000
