from __future__ import annotations

from fastapi.responses import HTMLResponse


def network_map_page() -> HTMLResponse:
    return HTMLResponse(
        r'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Nmap Terrain Analyzer · Network Map</title>
  <style>
    :root { color-scheme:dark; --bg:#08141d; --panel:#0f1d27; --line:#243b47; --text:#e7eef8; --muted:#9eb0b8; --accent:#57d6bf; --device:#5cc8ff; --interface:#ff9f68; --subnet:#c99cff; --host:#61d095; --gateway:#f4c95d; --bad:#ff7b7b; }
    * { box-sizing:border-box; } body { margin:0; background:linear-gradient(135deg,#08141d,#10242e); color:var(--text); font:14px/1.45 system-ui,-apple-system,Segoe UI,sans-serif; }
    header { max-width:1180px; margin:0 auto; padding:26px 0 20px; border-bottom:1px solid var(--line); } h1 { margin:0 0 4px; font-size:27px; } h2 { margin:0 0 11px; font-size:18px; } h3 { margin:18px 0 8px; font-size:14px; } .sub,.meta { color:var(--muted); } .sub { margin:0; } .eyebrow { color:var(--accent); font-weight:700; letter-spacing:.08em; text-transform:uppercase; font-size:11px; }
    .nav { display:flex; flex-wrap:wrap; gap:8px; margin-top:18px; } .nav a { display:inline-flex; align-items:center; border:1px solid #315264; background:#142d38; color:#b9cadc; border-radius:7px; padding:9px 13px; text-decoration:none; font-weight:700; } .nav a:hover { background:#1b4b57; color:#fff; } .nav a.active { background:var(--accent); border-color:var(--accent); color:#07171b; }
    main { max-width:1180px; margin:0 auto; padding:24px 0 60px; } .summary { display:grid; grid-template-columns:repeat(6,minmax(0,1fr)); gap:10px; margin-bottom:18px; } .stat,.panel { background:rgba(15,29,39,.95); border:1px solid var(--line); border-radius:12px; box-shadow:0 10px 35px rgba(0,0,0,.18); } .stat { padding:13px 15px; } .stat strong { display:block; font-size:22px; color:#fff; } .stat span { color:var(--muted); font-size:12px; }
    .workspace { display:grid; grid-template-columns:minmax(0,1fr) 310px; gap:18px; align-items:start; } .panel { padding:16px; } .map-toolbar { display:flex; flex-wrap:wrap; gap:9px; align-items:center; margin-bottom:12px; } .map-toolbar input { flex:1 1 240px; } .map-toolbar select { flex:0 1 270px; } input,select { background:#0b1526; color:var(--text); border:1px solid #365071; border-radius:7px; padding:9px 10px; font:inherit; } input:focus,select:focus { outline:2px solid rgba(87,214,191,.3); border-color:var(--accent); }
    button { border:1px solid #3b6f91; background:#174665; color:#fff; border-radius:7px; padding:9px 12px; font:inherit; font-weight:700; cursor:pointer; } button:hover { background:#1d587d; } button.secondary { background:transparent; border-color:#49617d; } button:disabled { opacity:.55; cursor:not-allowed; }
    #notice { min-height:22px; color:var(--muted); } #notice.bad { color:var(--bad); } #notice.good { color:var(--accent); } .legend { display:flex; flex-wrap:wrap; gap:13px; color:var(--muted); font-size:12px; margin:0 0 10px; } .legend span { display:inline-flex; align-items:center; gap:6px; } .dot { width:10px; height:10px; border-radius:50%; display:inline-block; } .line { width:24px; border-top:2px solid #63808d; } .line.dashed { border-top-style:dashed; }
    .canvas { min-height:650px; max-height:900px; overflow:auto; background:#09151d; border:1px solid #203944; border-radius:9px; } svg { display:block; min-width:1120px; width:100%; } .edge { fill:none; stroke:#58717d; stroke-width:1.7; opacity:.78; } .edge.inferred { stroke-dasharray:7 6; opacity:.58; } .edge-label { fill:#ffc08d; font-size:11px; font-weight:700; paint-order:stroke; stroke:#09151d; stroke-width:5px; stroke-linejoin:round; } .node { cursor:pointer; transition:opacity .15s; } .node rect { fill:#10232d; stroke-width:2; rx:9; } .node:hover rect,.node.selected rect { filter:brightness(1.35); stroke-width:3; } .node.device rect { stroke:var(--device); } .node.subnet rect,.node.subnet_group rect { stroke:var(--subnet); stroke-dasharray:5 3; } .node.subnet.needs-scan rect { stroke:var(--gateway); } .node.subnet.needs-scan .node-subtitle { fill:#f4c95d; } .node.host rect { stroke:var(--host); } .node.gateway rect { stroke:var(--gateway); } .node-title { fill:#f3f8fc; font-size:13px; font-weight:750; } .node-subtitle { fill:#90a9b4; font-size:11px; } .node.filtered { opacity:.12; }
    .details-empty { color:var(--muted); padding:12px 0; } .identity { padding-bottom:12px; border-bottom:1px solid var(--line); } .identity code { color:#bdeefa; } .badge { display:inline-block; margin:2px 5px 2px 0; padding:3px 7px; border-radius:999px; background:#173743; color:#bfe7f1; font-size:11px; } .kv { display:grid; grid-template-columns:90px 1fr; gap:6px 9px; font-size:12px; margin-top:12px; } .kv span:nth-child(odd) { color:var(--muted); } .list { margin:7px 0 0; padding-left:18px; color:#cce2eb; font-size:12px; } .source { display:block; border:1px solid #294753; border-radius:7px; padding:8px; margin-top:7px; color:#bfe8f4; text-decoration:none; overflow-wrap:anywhere; } .source:hover { background:#15323d; } table { width:100%; border-collapse:collapse; font-size:11px; } th,td { padding:6px 4px; border-bottom:1px solid #263f49; text-align:left; vertical-align:top; } th { color:var(--muted); } .file-browser { margin:4px 0 12px; padding:10px 12px; border:1px solid #294753; border-radius:8px; background:#0b1b24; color:#cce2eb; font-size:12px; } .file-browser h3 { margin:0 0 5px; } .file-browser ul { margin:6px 0 0; padding-left:17px; } .file-browser li { margin:4px 0; } .file-browser a { color:#8be1d0; } .file-browser .meta { color:var(--muted); }
    .warnings { margin-top:15px; } .warning { background:#342d17; border:1px solid #6d5b25; border-radius:8px; padding:9px 11px; color:#f2d78a; margin-top:7px; } .sr-only { position:absolute; width:1px; height:1px; padding:0; margin:-1px; overflow:hidden; clip:rect(0,0,0,0); white-space:nowrap; border:0; }
    @media (max-width:1200px) { header,main { padding-left:4vw; padding-right:4vw; } } @media (max-width:900px) { .workspace { grid-template-columns:1fr; } .summary { grid-template-columns:repeat(2,1fr); } }
    header { position:sticky; top:0; z-index:100; padding-top:16px; padding-bottom:14px; background:rgba(8,20,29,.96); backdrop-filter:blur(14px); box-shadow:0 9px 24px rgba(0,0,0,.38); } header h1 { font-size:25px; } .nav { margin-top:12px; }
  </style>
</head>
<body>
  <header><div class="eyebrow">Proof of concept · no authentication</div><h1>Network Map</h1><p class="sub">Visualize hosts, routed subnets, and network devices from saved analyzer evidence.</p><nav class="nav" aria-label="Primary"><a href="/scans">Nmap Scans</a><a href="/analysis">Analyze Results</a><a href="/device-config">Device Configurations</a><a class="active" href="/network-map" aria-current="page">Network Map</a></nav></header>
  <main>
    <section class="summary"><div class="stat"><strong id="deviceCount">—</strong><span>Network devices</span></div><div class="stat"><strong id="interfaceCount">—</strong><span>Interfaces</span></div><div class="stat"><strong id="subnetCount">—</strong><span>Subnet groups</span></div><div class="stat"><strong id="hostCount">—</strong><span>Observed hosts</span></div><div class="stat"><strong id="edgeCount">—</strong><span>Relationships</span></div><div class="stat"><strong id="sourceCount">—</strong><span>Evidence observations</span></div></section>
    <div class="workspace">
      <section class="panel"><div class="map-toolbar"><label for="fileNavigator" class="sr-only">Stored files</label><select id="fileNavigator"><option value="">Browse stored files…</option></select><input id="search" type="search" placeholder="Find an IP, hostname, vendor, OS, interface, or service"><button id="refresh">Refresh map</button><button id="expandAll" class="secondary">Expand all hosts</button><button id="collapseAll" class="secondary">Collapse hosts</button><button id="clear" class="secondary">Clear filter</button></div><div id="fileBrowser" class="file-browser" hidden></div><div id="notice" role="status" aria-live="polite">Loading saved topology evidence…</div><div class="legend"><span><i class="dot" style="background:var(--gateway)"></i>Boundary / gateway</span><span><i class="dot" style="background:var(--device)"></i>Router / firewall</span><span><i class="dot" style="background:var(--subnet)"></i>Collapsible subnet</span><span><i class="dot" style="background:var(--host)"></i>Host</span><span><i class="line"></i>Interface label on connection</span><span><i class="line dashed"></i>Inferred</span></div><div class="canvas"><svg id="map" role="img" aria-label="Hierarchical network topology generated from saved analyzer evidence"></svg></div><div id="warnings" class="warnings"></div></section>
      <aside class="panel" id="details"><h2>Device details</h2><div class="details-empty">Select a device, subnet, or host on the map.</div></aside>
    </div>
  </main>
<script>
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const svgNS='http://www.w3.org/2000/svg'; let topology=null, selectedId=null, viewNodes=new Map(), groupHosts=new Map(), storedLocations=[]; const expandedGroups=new Set();
function svgEl(name,attrs={}) { const element=document.createElementNS(svgNS,name); for(const [key,value] of Object.entries(attrs)) element.setAttribute(key,String(value)); return element; }
function short(value,length=27) { value=String(value||''); return value.length>length?value.slice(0,length-1)+'…':value; }
function nodeSearch(node) { return [node.label,node.ip,node.network,node.address,...(node.addresses||[]),node.interface,node.hostname,node.role,node.vendor,node.os,...(node.interfaces||[]).flatMap(i=>[i.name,i.address,...(i.addresses||[])]),...(node.services||[]).flatMap(s=>[s.port,s.protocol,s.service,s.product,s.version])].join(' ').toLowerCase(); }
function buildGroups() {
  groupHosts=new Map(); if(!topology)return;
  const hosts=topology.nodes.filter(node=>node.kind==='host'),hostIds=new Set(hosts.map(node=>node.id)),mapped=new Set();
  for(const subnet of topology.nodes.filter(node=>node.kind==='subnet')) groupHosts.set(subnet.id,[]);
  for(const edge of topology.edges.filter(edge=>edge.relation==='subnet_membership')) { if(!hostIds.has(edge.source)||!groupHosts.has(edge.target))continue; const host=topology.nodes.find(node=>node.id===edge.source); if(host){groupHosts.get(edge.target).push(host);mapped.add(host.id);} }
  const unmapped=hosts.filter(host=>!mapped.has(host.id)); if(unmapped.length)groupHosts.set('group:unmapped',unmapped);
}
function buildView() {
  buildGroups(); const query=$('search').value.trim().toLowerCase(),hostIds=new Set(topology.nodes.filter(node=>node.kind==='host').map(node=>node.id));
  const interfaces=new Map(topology.nodes.filter(node=>node.kind==='interface').map(node=>[node.id,node]));
  const nodes=topology.nodes.filter(node=>node.kind!=='host'&&node.kind!=='interface').map(node=>({...node,host_count:(groupHosts.get(node.id)||[]).length}));
  if(groupHosts.has('group:unmapped')) nodes.push({id:'group:unmapped',kind:'subnet_group',label:'Unmapped hosts',network:null,host_count:groupHosts.get('group:unmapped').length,sources:[]});
  const edges=topology.edges.filter(edge=>!hostIds.has(edge.source)&&!hostIds.has(edge.target)&&!interfaces.has(edge.source)&&!interfaces.has(edge.target)).map(edge=>({...edge}));
  for(const [interfaceId,iface] of interfaces) {
    const owner=topology.edges.find(edge=>edge.relation==='owns_interface'&&edge.target===interfaceId)?.source||iface.device_id;
    if(!owner)continue;
    const addresses=iface.addresses?.length?iface.addresses:(iface.address?[iface.address]:[]),interfaceLabel=[iface.interface||iface.label,...addresses].filter(Boolean).join(' · ');
    for(const outgoing of topology.edges.filter(edge=>edge.source===interfaceId&&!hostIds.has(edge.target))) edges.push({...outgoing,id:`collapsed:${outgoing.id}`,source:owner,label:interfaceLabel||outgoing.label,interface_label:true});
  }
  for(const [groupId,hosts] of groupHosts) {
    const visible=expandedGroups.has(groupId)?hosts:(query?hosts.filter(host=>nodeSearch(host).includes(query)):[]);
    for(const host of visible) { nodes.push(host); const existing=topology.edges.find(edge=>edge.relation==='subnet_membership'&&edge.source===host.id&&edge.target===groupId); edges.push(existing?{...existing}:{id:`edge:${groupId}:${host.id}`,source:groupId,target:host.id,relation:'unmapped_membership',label:'unmapped observation',confidence:'inferred'}); }
  }
  viewNodes=new Map(nodes.map(node=>[node.id,node])); return {nodes,edges};
}
function placeLevel(items,y,width,positions,orderKey=null) { const ordered=[...items].sort((a,b)=>{const ak=orderKey?orderKey(a):String(a.label),bk=orderKey?orderKey(b):String(b.label);return String(ak).localeCompare(String(bk))||String(a.label).localeCompare(String(b.label));}),gap=width/(ordered.length+1); ordered.forEach((node,index)=>{const w=node.kind==='host'?190:210;positions.set(node.id,{x:gap*(index+1)-w/2,y,w,h:56});}); }
function renderMap() {
  const svg=$('map'); svg.replaceChildren(); if(!topology||!topology.nodes.length) { svg.setAttribute('viewBox','0 0 1120 720'); const text=svgEl('text',{x:560,y:340,'text-anchor':'middle',fill:'#9eb0b8'}); text.textContent='No saved topology evidence is available yet.'; svg.append(text); return; }
  const view=buildView(),devices=view.nodes.filter(n=>n.kind==='device'||n.kind==='gateway'),boundary=devices.filter(n=>n.kind==='gateway'||n.role==='firewall'),core=devices.filter(n=>!boundary.includes(n)),subnets=view.nodes.filter(n=>n.kind==='subnet'||n.kind==='subnet_group'),hosts=view.nodes.filter(n=>n.kind==='host');
  if(!boundary.length&&core.length){boundary.push(...core);core.length=0;} const widest=Math.max(boundary.length,core.length,subnets.length,hosts.length,5),width=Math.max(1120,100+widest*230),height=hosts.length?650:520; svg.setAttribute('viewBox',`0 0 ${width} ${height}`); svg.style.width=width+'px';svg.style.height=height+'px';
  const positions=new Map(); placeLevel(boundary,35,width,positions); placeLevel(core,165,width,positions); const deviceOrder=new Map([...boundary,...core].map((node,index)=>[node.id,index])); const subnetOrder=node=>{const owners=(node.owners||[]).map(id=>deviceOrder.has(id)?deviceOrder.get(id):999);return owners.length?Math.min(...owners):999;}; const hostOrder=node=>{for(const [groupId,items] of groupHosts){if(items.some(item=>item.id===node.id)){const group=view.nodes.find(item=>item.id===groupId);return `${subnetOrder(group||{})}:${node.label}`;}}return `999:${node.label}`;}; placeLevel(subnets,320,width,positions,subnetOrder); placeLevel(hosts,475,width,positions,hostOrder);
  for(const edge of view.edges) { let a=positions.get(edge.source),b=positions.get(edge.target); if(!a||!b)continue; if(a.y>b.y)[a,b]=[b,a]; const x1=a.x+a.w/2,y1=a.y+a.h,x2=b.x+b.w/2,y2=b.y,mid=y1+(y2-y1)/2; const path=svgEl('path',{d:`M ${x1} ${y1} V ${mid} H ${x2} V ${y2}`,class:`edge ${edge.confidence==='inferred'?'inferred':''}`}); const tooltip=svgEl('title');tooltip.textContent=`${edge.label} · ${edge.confidence}${edge.evidence?' · '+edge.evidence:''}`;path.append(tooltip);svg.append(path); if(edge.interface_label){const label=svgEl('text',{x:(x1+x2)/2,y:mid-6,'text-anchor':'middle',class:'edge-label'});label.textContent=short(edge.label,48);const labelTip=svgEl('title');labelTip.textContent=edge.label;label.append(labelTip);svg.append(label);} }
  for(const node of view.nodes) { const pos=positions.get(node.id); if(!pos)continue; const emptySubnet=node.kind==='subnet'&&node.host_count===0,classes=`node ${node.kind}${node.id===selectedId?' selected':''}${emptySubnet?' needs-scan':''}`; const group=svgEl('g',{class:classes,'data-node':node.id,tabindex:'0',role:'button','aria-label':`${node.kind} ${node.label}`}); const rect=svgEl('rect',{x:pos.x,y:pos.y,width:pos.w,height:pos.h}); const title=svgEl('text',{x:pos.x+12,y:pos.y+22,class:'node-title'}); title.textContent=short(node.label); const subtitle=svgEl('text',{x:pos.x+12,y:pos.y+42,class:'node-subtitle'}); if(node.kind==='subnet'||node.kind==='subnet_group') subtitle.textContent=node.host_count===0?'0 hosts · characterization needed':`${node.host_count} host${node.host_count===1?'':'s'} · ${expandedGroups.has(node.id)?'collapse':'expand'}`; else subtitle.textContent=short(node.address||node.ip||node.network||node.role||node.kind); group.append(rect,title,subtitle); group.onclick=()=>activateNode(node.id); group.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activateNode(node.id)}};svg.append(group); }
  applyFilter();
}
function formatSource(source) { const body=`<strong>${esc(source.label)}</strong><br><span class="meta">${esc(source.kind)}${source.timestamp?' · '+esc(source.timestamp):''}</span>`; return source.url?`<a class="source" href="${esc(source.url)}" target="_blank" rel="noopener">${body}</a>`:`<div class="source">${body}</div>`; }
function formatBytes(value) { const n=Number(value||0); if(n<1024)return `${n} B`; if(n<1024*1024)return `${(n/1024).toFixed(1)} KiB`; return `${(n/1024/1024).toFixed(1)} MiB`; }
function showStoredLocation(location) { const browser=$('fileBrowser'); if(!location){browser.hidden=true; browser.innerHTML=''; return;} const files=location.files||[]; browser.hidden=false; browser.innerHTML=`<h3>${esc(location.label||location.folder)}</h3><div class="meta">${esc(location.folder||'')} · ${esc(location.status||'stored')}</div>${files.length?`<ul>${files.map(file=>`<li>${file.download_url?`<a href="${esc(file.download_url)}" target="_blank" rel="noopener">${esc(file.name)}</a>`:esc(file.name)} <span class="meta">(${formatBytes(file.size_bytes)} · ${esc(file.modified_at||'')})</span></li>`).join('')}</ul>`:'<div class="details-empty">No files are stored in this location.</div>'}`; }
async function loadStoredFiles() { try { const response=await fetch('/api/stored-files?limit=300'); const data=await response.json(); if(!response.ok)throw new Error(data.detail||'Stored files could not be loaded'); storedLocations=data.locations||[]; const select=$('fileNavigator'); select.innerHTML='<option value="">Browse stored files…</option>'+storedLocations.map((location,index)=>`<option value="${index}">${location.category==='scan'?'Scan':location.category==='device'?'Device config':'Nmap import'} · ${location.label} · ${location.folder}</option>`).join(''); } catch(error) { $('fileNavigator').innerHTML='<option value="">Stored files unavailable</option>'; } }
function showDetails(node) { if(!node)return; const services=node.services||[],interfaces=node.interfaces||[],routes=node.routes||[],sources=node.sources||[],isGroup=node.kind==='subnet'||node.kind==='subnet_group',needsScan=node.kind==='subnet'&&node.host_count===0,addresses=node.addresses?.length?node.addresses.join(', '):(node.ip||node.network||node.address||'—'); $('details').innerHTML=`<h2>${esc(node.label)}</h2><div class="identity"><span class="badge">${esc(node.kind.replace('_',' '))}</span>${node.role?`<span class="badge">${esc(node.role)}</span>`:''}${node.state?`<span class="badge">${esc(node.state)}</span>`:''}<div class="kv"><span>Address${node.addresses?.length>1?'es':''}</span><strong><code>${esc(addresses)}</code></strong><span>Hostname</span><strong>${esc(node.hostname||'—')}</strong><span>Vendor</span><strong>${esc(node.vendor||'—')}</strong><span>MAC</span><strong>${esc(node.mac||'—')}</strong><span>OS</span><strong>${esc(node.os||'—')}</strong>${isGroup?`<span>Observed hosts</span><strong>${esc(node.host_count||0)}</strong>`:''}</div></div>${needsScan?'<div class="warning">This subnet is present in device configuration evidence but has no observed hosts. Network characterization is still needed.</div>':''}${isGroup&&node.host_count?`<div class="actions" style="margin-top:12px"><button id="toggleGroup">${expandedGroups.has(node.id)?'Collapse':'Expand'} ${node.host_count} host${node.host_count===1?'':'s'}</button></div>`:''}${services.length?`<h3>Open services</h3><table><thead><tr><th>Port</th><th>Service</th><th>Product</th></tr></thead><tbody>${services.map(s=>`<tr><td>${esc(s.port)}/${esc(s.protocol||'')}</td><td>${esc(s.service||'—')}</td><td>${esc([s.product,s.version].filter(Boolean).join(' ')||'—')}</td></tr>`).join('')}</tbody></table>`:''}${interfaces.length?`<h3>Interfaces</h3><ul class="list">${interfaces.map(i=>`<li>${esc(i.name||'interface')} · ${esc(i.addresses?.join(', ')||i.address||'—')}</li>`).join('')}</ul>`:''}${routes.length?`<h3>Parsed routes</h3><ul class="list">${routes.map(r=>`<li>${esc(r.network)}${r.via?' via '+esc(r.via):' directly connected'}${r.interface?' · '+esc(r.interface):''}</li>`).join('')}</ul>`:''}<h3>Evidence</h3>${sources.length?sources.map(formatSource).join(''):'<div class="details-empty">No evidence link is available.</div>'}`; const toggle=$('toggleGroup');if(toggle)toggle.onclick=()=>toggleGroup(node.id); }
function toggleGroup(id) { if(expandedGroups.has(id))expandedGroups.delete(id);else expandedGroups.add(id);renderMap();showDetails(viewNodes.get(id)); }
function activateNode(id) { selectedId=id; const node=viewNodes.get(id); if((node?.kind==='subnet'||node?.kind==='subnet_group')&&node.host_count)toggleGroup(id);else{renderMap();showDetails(viewNodes.get(id)||node);} }
function applyFilter() { const query=$('search').value.trim().toLowerCase(); document.querySelectorAll('[data-node]').forEach(group=>{const node=viewNodes.get(group.dataset.node);group.classList.toggle('filtered',Boolean(query&&node&&!nodeSearch(node).includes(query)));}); }
async function loadMap() { $('refresh').disabled=true; $('notice').textContent='Reading saved Nmap and device-configuration evidence…'; $('notice').className=''; try { const response=await fetch('/api/network-map');const data=await response.json();if(!response.ok)throw new Error(data.detail||'Network map could not be loaded');topology=data;const s=data.summary;$('deviceCount').textContent=(s.devices||0)+(s.gateways||0);$('interfaceCount').textContent=s.interfaces||0;$('subnetCount').textContent=s.subnets||0;$('hostCount').textContent=s.hosts||0;$('edgeCount').textContent=s.relationships||0;$('sourceCount').textContent=(s.nmap_records_read||0)+(s.configuration_records_read||0);$('notice').textContent=`Map generated ${data.generated_at}. Subnets are ordered beneath their owning devices; interface names and addresses are labeled on the connection lines.`;$('notice').className='good';$('warnings').innerHTML=(data.warnings||[]).map(w=>`<div class="warning">${esc(w)}</div>`).join('');renderMap();if(selectedId&&!viewNodes.has(selectedId)){selectedId=null;$('details').innerHTML='<h2>Device details</h2><div class="details-empty">Select a device, subnet, or host on the map.</div>';} } catch(error){$('notice').textContent=error.message;$('notice').className='bad';} finally{$('refresh').disabled=false; await loadStoredFiles();} }
$('refresh').onclick=loadMap;$('search').oninput=renderMap;$('clear').onclick=()=>{$('search').value='';renderMap();};$('expandAll').onclick=()=>{buildGroups();for(const [id,hosts] of groupHosts)if(hosts.length)expandedGroups.add(id);renderMap();};$('collapseAll').onclick=()=>{expandedGroups.clear();renderMap();};$('fileNavigator').onchange=()=>showStoredLocation(storedLocations[Number($('fileNavigator').value)]);loadMap();
</script>
</body></html>'''
    )
