from fastapi.responses import HTMLResponse


def network_scope_page() -> HTMLResponse:
    return HTMLResponse(r'''<!doctype html>
<html class="nct-shell-loading" lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>NCT · Network Scopes</title><style id="nct-shell-bootstrap">html.nct-shell-loading body{visibility:hidden}</style>
<style>:root{color-scheme:dark;--bg:#09131c;--panel:#112330;--line:#304955;--text:#e8f2f6;--muted:#abc0cb;--accent:#62d9ba;--bad:#ff9b9b}*{box-sizing:border-box}[hidden]{display:none!important}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.5 system-ui}header{padding:20px 4vw;border-bottom:1px solid var(--line)}main{max-width:1180px;margin:auto;padding:30px 24px}.grid{display:grid;grid-template-columns:minmax(300px,1fr) minmax(360px,1.3fr);gap:18px}.panel{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:22px;margin-bottom:18px}h1{margin:0;font-size:30px}h2{margin:0 0 12px;font-size:19px}p,.meta{color:var(--muted)}li{margin:7px 0}label{display:grid;gap:5px;margin:12px 0;font-weight:700}input,textarea,button{font:inherit;border:1px solid var(--line);border-radius:8px;padding:10px 12px;background:#0b1b26;color:var(--text)}textarea{min-height:100px;resize:vertical}button{cursor:pointer;font-weight:700;background:#193445}button.primary{background:var(--accent);color:#09251d}button.danger{background:#592831;color:#ffd8d8}button:disabled{opacity:.5;cursor:not-allowed}.actions{display:flex;flex-wrap:wrap;gap:10px}.scope{border:1px solid var(--line);border-radius:9px;padding:14px;margin:10px 0}.scope[aria-current=true]{border-color:var(--accent)}.scope h3{margin:0}.badge{display:inline-block;border:1px solid var(--line);border-radius:20px;padding:2px 9px;margin-left:7px;color:var(--muted)}code{overflow-wrap:anywhere}.good{color:var(--accent)}.bad{color:var(--bad)}#history{padding-left:20px}.notice{border-left:3px solid var(--accent);padding-left:12px}@media(max-width:800px){.grid{grid-template-columns:1fr}main{padding:20px 14px}}</style>
<script src="/assets/nct-session.js"></script></head><body><header><strong>NCT</strong> · Network Correlation &amp; Triage</header><main>
<p>Settings / Network Scopes</p><h1>Network scopes</h1>
<p class="notice">Scopes keep the same IP address separate when it appears in different network contexts. This page manages scope identity only; it does not assign evidence, start scans, contact devices, or change Saved Networks.</p>
<section class="panel" id="scopeHelp"><h2>When to create a scope</h2>
<p>A scope represents one network context in which an address has a consistent meaning. Create separate scopes for contexts such as guest and office networks, lab and production, different customers, or disconnected sites that may reuse the same addresses.</p>
<ul><li><strong>Reuse a scope</strong> for later scans and collections from the same network context. A new scan by itself does not require a new scope.</li>
<li><strong>Use the hierarchy scope → named subnet → CIDR → IP address.</strong> For example, “AFB Dev” can later contain “Development Servers” at <code>10.50.15.0/24</code> and “Development Clients” at <code>10.50.16.0/24</code>. This page creates only the “AFB Dev” scope identity; subnet and CIDR association comes next.</li>
<li><strong>Choose a recognizable label</strong> such as “Guest Wi-Fi — Building A.” Use the description for the location, owner, mission, or boundary that makes it distinct.</li>
<li><strong>Manage</strong> opens the label, description, permanent ID, and change history. Editing the display text does not change the scope identity.</li></ul>
<p class="notice"><strong>Current foundation status:</strong> creating a scope prepares its identity. Analysts can associate a Saved Network with an active scope for future scans, and can separately assign or correct the context of one exact manual Nmap upload from Analyze. In-tool scans made only from Saved Networks in one active scope retain that reviewed context with their evidence. Mixed or manual scan targets remain unscoped. These assignments still do not change current Analyze, Hunt, Reach, or Map results.</p>
<p>Edits and archives require a reason, which is kept in history. Archiving permanently removes the scope from future choices in this version and cannot currently be undone; its existing identity, history, and evidence references remain retained.</p></section>
<div class="grid"><section class="panel"><h2 id="formTitle">Create a network scope</h2><form id="editor">
<input id="scopeId" type="hidden"><input id="version" type="hidden">
<label>Label<input id="label" maxlength="100" required placeholder="Example: Guest Wi-Fi — Building A"></label>
<label>Description<textarea id="description" maxlength="500" placeholder="What makes this network context distinct?"></textarea></label>
<label id="reasonLabel" hidden>Reason for change<input id="reason" maxlength="500" placeholder="Why is this metadata changing?" disabled></label>
<div class="actions"><button class="primary" id="save">Create scope</button><button type="button" id="newScope">Clear</button><button class="danger" type="button" id="archive" hidden>Archive scope</button></div></form>
<p id="status" role="status" aria-live="polite"></p></section>
<section class="panel"><h2>Registered scopes</h2><label><span><input id="showArchived" type="checkbox"> Show archived scopes</span></label><div id="scopes"><p>Loading…</p></div></section></div>
<section class="panel"><h2>Selected scope history</h2><p class="meta">Every creation, edit, and archive keeps a permanent before/after record.</p><ol id="history"><li>Select a scope to inspect its history.</li></ol></section>
<a href="/">Return to workspace</a></main><script>
(()=>{
const $=id=>document.getElementById(id);let records=[],selected=null;
async function api(url,options={}){const response=await fetch(url,{credentials:'same-origin',...options});let data={};try{data=await response.json()}catch(_){}if(!response.ok)throw Error(data.detail||'Request failed');return data}
function setStatus(message,kind=''){ $('status').textContent=message;$('status').className=kind }
function reset(){selected=null;$('editor').reset();$('scopeId').value='';$('version').value='';$('formTitle').textContent='Create a network scope';$('save').textContent='Create scope';$('save').disabled=false;$('reasonLabel').hidden=true;$('reason').required=false;$('reason').disabled=true;$('archive').hidden=true;$('history').innerHTML='<li>Select a scope to inspect its history.</li>';render()}
async function selectScope(id){selected=records.find(item=>item.scope_id===id)||null;if(!selected)return;$('scopeId').value=selected.scope_id;$('version').value=selected.version;$('label').value=selected.label;$('description').value=selected.description;$('reason').value='';$('formTitle').textContent=selected.active?'Edit network scope':'Archived network scope';$('save').textContent='Save changes';$('reasonLabel').hidden=false;$('reason').disabled=false;$('reason').required=true;$('save').disabled=!selected.active;$('archive').hidden=!selected.active;render();const history=await api(`/api/network-scopes/${encodeURIComponent(id)}/history`);$('history').replaceChildren();for(const event of history){const li=document.createElement('li'),strong=document.createElement('strong'),detail=document.createElement('div');strong.textContent=event.event+' · version '+event.new_version;detail.className='meta';detail.textContent=`${event.actor} · ${new Date(event.recorded_at).toLocaleString()} · ${event.reason}`;li.append(strong,detail);$('history').append(li)}}
function render(){const root=$('scopes');root.replaceChildren();if(!records.length){const p=document.createElement('p');p.textContent='No scopes match this view.';root.append(p);return}for(const item of records){const card=document.createElement('article');card.className='scope';card.setAttribute('aria-current',String(item.scope_id===selected?.scope_id));const title=document.createElement('h3'),badge=document.createElement('span'),description=document.createElement('p'),identity=document.createElement('code'),button=document.createElement('button');title.textContent=item.label;badge.className='badge';badge.textContent=item.active?'Active':'Archived';title.append(badge);description.textContent=item.description||'No description';identity.textContent=item.scope_id;button.textContent='Manage';button.type='button';button.onclick=()=>selectScope(item.scope_id);card.append(title,description,identity,document.createElement('br'),button);root.append(card)}}
async function load(){try{const selectedId=selected?.scope_id||null;records=await api('/api/network-scopes?include_archived='+$('showArchived').checked);if(selectedId){selected=records.find(item=>item.scope_id===selectedId)||null;if(!selected){reset();return}}render()}catch(error){setStatus(error.message,'bad')}}
$('editor').onsubmit=async event=>{event.preventDefault();setStatus(selected?'Saving changes…':'Creating scope…');try{if(selected){const saved=await api(`/api/network-scopes/${encodeURIComponent(selected.scope_id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected_version:selected.version,label:$('label').value,description:$('description').value,reason:$('reason').value})});await load();await selectScope(saved.scope_id);setStatus('Scope updated. Existing evidence identity was not changed.','good')}else{const saved=await api('/api/network-scopes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label:$('label').value,description:$('description').value,reason:'Created through Network Scopes settings'})});await load();await selectScope(saved.scope_id);setStatus('Scope created. It is not assigned to evidence yet.','good')}}catch(error){setStatus(error.message,'bad')}};
$('archive').onclick=async()=>{if(!selected||!confirm(`Archive ${selected.label}? Existing history remains, but new evidence cannot use this scope.`))return;const reason=$('reason').value.trim();if(!reason){setStatus('Enter a reason before archiving.','bad');$('reason').focus();return}const scopeId=selected.scope_id;try{await api(`/api/network-scopes/${encodeURIComponent(scopeId)}/archive`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected_version:selected.version,reason})});$('showArchived').checked=true;await load();await selectScope(scopeId);setStatus('Scope archived. Existing evidence and history were retained.','good')}catch(error){setStatus(error.message,'bad')}};
$('newScope').onclick=reset;$('showArchived').onchange=load;load();
})();
</script></body></html>''')
