from fastapi.responses import HTMLResponse


def storage_page() -> HTMLResponse:
    return HTMLResponse(r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>NCT · System Health</title>
<style>
:root{color-scheme:dark;--bg:#09131c;--panel:#112330;--line:#304955;--text:#e8f2f6;--muted:#abc0cb;--accent:#62d9ba}
#nct-page-context{display:none!important}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.5 system-ui}header{padding:20px 4vw;border-bottom:1px solid var(--line)}main{max-width:1180px;margin:auto;padding:30px 24px}h1{font-size:30px;margin:0}h2{font-size:19px;margin:0 0 12px}h3{font-size:16px;margin:20px 0 8px}p{color:var(--muted)}.panel,.metric{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:22px;margin-bottom:18px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.metric strong{display:block;font-size:29px;margin-top:12px}.metric span{color:var(--muted)}.actions{display:flex;flex-wrap:wrap;gap:12px;margin:24px 0}button{font:inherit;font-weight:650;border:1px solid var(--line);border-radius:8px;padding:11px 16px;background:#193445;color:var(--text);cursor:pointer}button.compact{padding:6px 10px;font-size:13px}button.primary{background:var(--accent);color:#09251d}button:disabled{opacity:.5;cursor:wait}dl{display:grid;grid-template-columns:1fr 1fr;gap:10px}dd{margin:0;text-align:right}dt{color:var(--muted)}.badge{display:inline-block;border:1px solid var(--accent);color:var(--accent);border-radius:30px;padding:4px 12px}.state{font-size:12px;font-weight:750;letter-spacing:.04em}.state.CURRENT{color:#75e6b8}.state.STALE{color:#ffd166}.state.UNKNOWN{color:#f5a6a6}.table-wrap{overflow:auto;border:1px solid var(--line);border-radius:9px}table{width:100%;border-collapse:collapse;min-width:760px}th,td{padding:11px 12px;text-align:left;border-bottom:1px solid var(--line);vertical-align:top}th{color:var(--muted);font-size:12px;text-transform:uppercase}tr:last-child td{border-bottom:0}.pager{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:14px}.pager div{display:flex;gap:8px}.panel-title{display:flex;align-items:center;justify-content:space-between;gap:12px}.hidden{display:none}.identifier{max-width:460px;overflow-wrap:anywhere;color:var(--muted);font:12px/1.45 ui-monospace,monospace}details summary{cursor:pointer;color:var(--accent)}#issues{overflow-wrap:anywhere}a{color:var(--accent)}@media(max-width:800px){.metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:450px){.metrics{grid-template-columns:1fr}main{padding:20px 14px}}
</style><script src="/assets/nct-session.js"></script></head><body>
<header><strong>NCT</strong> · Network Correlation &amp; Triage</header><main>
<p>Settings / System Health</p><h1>Evidence storage</h1>
<p>Inspect retained evidence and duplicate copies before planning a cleanup. Scan and collection history stay intact.</p>
<div class="actions"><button class="primary" id="inspect">Run storage dry run</button><button id="backfill">Backfill existing evidence</button></div>
<p>Backfill registers historical evidence without removing originals. It may temporarily increase used space until a future verified compaction step is available.</p>
<p id="status" role="status" aria-live="polite">Loading storage status…</p>
<div class="metrics">
<div class="metric"><span>Used space</span><strong id="used">—</strong><small>Retained data folder</small></div>
<div class="metric"><span>Unique evidence</span><strong id="unique">—</strong><small id="uniqueCount">Awaiting inspection</small></div>
<div class="metric"><span>Duplicate copies</span><strong id="duplicate">—</strong><small>Already-shared files excluded</small></div>
<div class="metric"><span>Potentially reclaimable</span><strong id="reclaimable">—</strong><small>Verified canonical copies only</small></div>
</div>
<section class="panel"><h2>Reusable analysis status</h2>
<p><strong>Current</strong> means the saved calculation rules match this build. It does not mean the source evidence is recent, intact, or still true on the network. Stale results remain retained and traceable. The saved rule version identifies the exact analysis instructions that created each result.</p>
<p id="analysisStatus" role="status" aria-live="polite">Loading saved calculation status.</p>
<div class="table-wrap"><table><thead><tr><th>Result type</th><th>Status</th><th>Saved rule version</th><th>Created</th><th>Explanation</th><th>Inputs</th></tr></thead><tbody id="analysisRows"></tbody></table></div>
<div class="pager"><span id="analysisPage">No saved results</span><div><button id="analysisPrevious">Previous</button><button id="analysisNext">Next</button></div></div>
</section>
<section class="panel"><h2>Saved calculation versions</h2>
<p>Review which exact calculation rules remain saved. Groups stay separate when their settings differ. The settings fingerprint is an internal identifier: matching fingerprints mean the stored settings match exactly. These counts are saved calculation results, not scans, evidence encounters, or jobs that need to run.</p>
<p id="versionStatus" role="status" aria-live="polite">Loading saved calculation versions.</p>
<div class="table-wrap"><table><thead><tr><th>Result type</th><th>Status</th><th>Saved rule version</th><th>Output format</th><th>Settings fingerprint</th><th>Saved results</th><th>Calculation dates</th><th>Details</th></tr></thead><tbody id="versionRows"></tbody></table></div>
<div class="pager"><span id="versionPage">No version groups loaded</span><div><button id="versionPrevious">Previous versions</button><button id="versionNext">Next versions</button></div></div>
<div class="hidden" id="versionResultsPanel"><h3 id="versionResultsTitle">Saved results in this version group</h3>
<p>This list contains calculation results with the exact family, rule version, output format, and settings shown above. It does not indicate whether evidence is recent or whether work needs to be rerun.</p>
<p id="versionResultsStatus" role="status" aria-live="polite"></p>
<div class="table-wrap"><table><thead><tr><th>Created</th><th>Exact result</th><th>Inputs</th></tr></thead><tbody id="versionResultRows"></tbody></table></div>
<div class="pager"><span id="versionResultsPage">No results loaded</span><div><button id="versionResultsPrevious">Previous results</button><button id="versionResultsNext">Next results</button></div></div></div>
</section>
<section class="panel hidden" id="dependencyPanel"><div class="panel-title"><h2 id="dependencyTitle">Inputs and source records</h2><button class="compact" id="dependencyClose">Close</button></div>
<p>A declared input is something this calculation used. A source record is one retained encounter that supplied exact registered bytes for that input. Source records are provenance, not additional calculation steps.</p>
<p>This view checks the saved relationships. It does not inspect source files, determine freshness, mark work stale, or rerun analysis.</p>
<p id="dependencyStatus" role="status" aria-live="polite">Choose a saved result to inspect its inputs.</p>
<div class="table-wrap"><table><thead><tr><th>Input role</th><th>Recorded type</th><th>Meaning</th><th>Exact identifier</th><th>Source records</th><th>Saved calculations</th></tr></thead><tbody id="dependencyRows"></tbody></table></div>
<div class="pager"><span id="dependencyPage">No inputs loaded</span><div><button id="dependencyPrevious">Previous inputs</button><button id="dependencyNext">Next inputs</button></div></div>
<div class="hidden" id="sourcePanel"><h3 id="sourceTitle">Source records</h3><p id="sourceStatus" role="status" aria-live="polite"></p>
<div class="table-wrap"><table><thead><tr><th>Recorded</th><th>Source</th><th>Filename</th><th>Actor</th><th>Size</th><th>Exact record</th></tr></thead><tbody id="sourceRows"></tbody></table></div>
<div class="pager"><span id="sourcePage">No source records loaded</span><div><button id="sourcePrevious">Previous records</button><button id="sourceNext">Next records</button></div></div></div>
<div class="hidden" id="impactPanel"><h3 id="impactTitle">Saved calculations using this input</h3>
<p>These are saved results that list this exact input directly. This does not show whether the source is recent or true on the network. It does not change status, mark results stale, or rerun analysis.</p>
<p>This shows direct recorded links only; calculations that used related inputs indirectly are not included.</p>
<p id="impactStatus" role="status" aria-live="polite"></p>
<div class="table-wrap"><table><thead><tr><th>Result type</th><th>Recorded relationship</th><th>Status</th><th>Created</th><th>Result details</th></tr></thead><tbody id="impactRows"></tbody></table></div>
<div class="pager"><span id="impactPage">No saved calculations loaded</span><div><button id="impactPrevious">Previous calculations</button><button id="impactNext">Next calculations</button></div></div></div>
</section>
<section class="panel"><h2>Storage breakdown</h2><p>Used space by folder or database file. Shared files are counted once, under the first folder inspected.</p><dl id="categories"><dt>Awaiting inspection</dt><dd>-</dd></dl></section>
<section class="panel"><h2>Compaction safety</h2><span class="badge" id="compaction">Not inspected</span>
<p id="detail">Dry run only. No evidence is deleted. Backfill registers historical files and may temporarily increase storage while keeping every original file.</p>
<dl><dt>Files inspected</dt><dd id="files">—</dd><dt>Verified evidence references</dt><dd id="references">—</dd><dt>Active collections skipped</dt><dd id="active">—</dd></dl>
<ul id="issues"></ul><p id="backfillResult"></p></section>
<section class="panel"><h2>Retention and coverage</h2><p>Automatic artifact pruning is disabled. All evidence is retained.</p>
<dl><dt>Passive telemetry storage</dt><dd>Not implemented</dd><dt>Pinned evidence accounting</dt><dd>Not implemented</dd></dl>
<p id="measurement">Figures are snapshots of file sizes. Filesystem overhead and compression are excluded.</p><p id="timestamp">No completed inspection yet.</p></section>
<a href="/">Return to workspace</a></main>
<script>
const byId=id=>document.getElementById(id);
function bytes(value){if(value==null)return '—';const units=['B','KiB','MiB','GiB','TiB'];let i=0;while(value>=1024&&i<4){value/=1024;i++;}return value.toFixed(i?1:0)+' '+units[i];}
let timer;
const analysisLimit=25,versionLimit=25,versionResultsLimit=25,dependencyLimit=25,sourceLimit=25,impactLimit=25;let analysisOffset=0,analysisDisplayedOffset=0,analysisRequestId=0,versionOffset=0,versionDisplayedOffset=0,versionRequestId=0,versionGroupId=null,versionRepresentative=null,versionResultsOffset=0,versionResultsDisplayedOffset=0,versionResultsRequestId=0,dependencyResultId=null,dependencyOffset=0,dependencyDisplayedOffset=0,dependencyRequestId=0,sourceRole=null,sourceOffset=0,sourceDisplayedOffset=0,sourceRequestId=0,impactRole=null,impactOffset=0,impactDisplayedOffset=0,impactRequestId=0;
function render(data){const running=data.status==='running';byId('inspect').disabled=running;byId('backfill').disabled=running;
byId('status').textContent=({not_run:'Run a dry run to inspect storage.',running:'Inspecting storage in the background. You can leave this page and return.',complete:'Storage inspection complete. No evidence was removed.',interrupted:'The previous operation was interrupted. Backfill can resume from its checkpoints.',failed:data.error||'Inspection failed. Retry when storage is available.'})[data.status]||data.status;
const r=data.report;if(r){byId('used').textContent=bytes(r.used_bytes);byId('unique').textContent=bytes(r.unique_artifact_bytes);byId('uniqueCount').textContent=r.unique_artifact_count+' distinct artifacts';byId('duplicate').textContent=bytes(r.duplicate_bytes);byId('reclaimable').textContent=bytes(r.reclaimable_bytes);byId('compaction').textContent=r.compaction.status==='blocked'?'Blocked — review required':'Dry run only — deletion disabled';byId('detail').textContent=r.compaction.detail;byId('files').textContent=r.files_inspected;byId('references').textContent=r.verified_references;byId('active').textContent=r.active_collections_skipped;byId('measurement').textContent=r.measurement;byId('timestamp').textContent='Snapshot: '+new Date(r.generated_at).toLocaleString();byId('issues').replaceChildren();for(const issue of r.issues){const li=document.createElement('li');li.textContent=issue;byId('issues').append(li);}if(r.issue_count>r.issues.length){const li=document.createElement('li');li.textContent=(r.issue_count-r.issues.length)+' additional issues';byId('issues').append(li);}}
if(r){byId('categories').replaceChildren();const labels={'analyzer.db':'SQLite database','analyzer.db-wal':'SQLite pending writes','analyzer.db-shm':'SQLite shared memory','artifacts':'Canonical evidence','device-configs':'Device collections','scan-runs':'Scan collections','imports':'Legacy imports','storage-health.json':'Storage inspection report'};for(const [name,size] of Object.entries(r.categories||{}).sort((a,b)=>b[1]-a[1])){const term=document.createElement('dt');term.textContent=labels[name]||name;const value=document.createElement('dd');value.textContent=bytes(size);byId('categories').append(term,value);}}
if(data.backfill){const b=data.backfill;byId('backfillResult').textContent='Backfill: '+b.completed+' registered; '+b.resumed_unchanged+' already registered or unchanged; '+b.issue_count+' issues. Originals retained.';}
clearTimeout(timer);if(running)timer=setTimeout(refresh,1500);}
async function refresh(){try{const response=await fetch('/api/system/storage');const data=await response.json();if(!response.ok)throw Error(data.detail||'Unable to load storage status');render(data);}catch(error){byId('status').textContent=error.message;byId('inspect').disabled=false;byId('backfill').disabled=false;}}
function detailIdentifier(value,label='Show exact identifier'){const details=document.createElement('details'),summary=document.createElement('summary'),code=document.createElement('div');summary.textContent=label;code.className='identifier';code.textContent=value;details.append(summary,code);return details;}
function dateText(value){const date=new Date(value);return Number.isNaN(date.getTime())?'Unreadable date':date.toLocaleString();}
function roleLabel(value){return ({nmap_xml:'Nmap XML',command_history:'Command history',configuration:'Configuration file',raw_output:'Raw collection output',manifest_semantics:'Collection details',selection_shape:'Evidence file choices'})[value]||value.replaceAll('_',' ');}
function renderAnalysis(data){byId('analysisRows').replaceChildren();for(const item of data.items){const row=document.createElement('tr'),label=document.createElement('td'),stateCell=document.createElement('td'),state=document.createElement('span'),version=document.createElement('td'),created=document.createElement('td'),reason=document.createElement('td'),action=document.createElement('td'),button=document.createElement('button');label.textContent=item.label;state.className='state '+item.state;state.textContent=item.state==='CURRENT'?'Current':item.state==='STALE'?'Stale':'Unknown';stateCell.append(state);version.textContent=item.analysis_version;created.textContent=new Date(item.generated_at).toLocaleString();reason.textContent=item.reasons.join(' ');button.className='compact';button.dataset.analysisInputs='';button.textContent='View inputs';button.onclick=()=>openDependencies(item.result_id,item.label);action.append(button);row.append(label,stateCell,version,created,reason,action);byId('analysisRows').append(row);}const start=data.total?data.offset+1:0,end=data.offset+data.items.length;byId('analysisPage').textContent=data.total?`Showing ${start}-${end} of ${data.total} saved results`:'No saved reusable results yet.';byId('analysisPrevious').disabled=data.offset===0;byId('analysisNext').disabled=!data.has_more;byId('analysisStatus').textContent=`This page: ${data.page_counts.CURRENT} current, ${data.page_counts.STALE} stale, ${data.page_counts.UNKNOWN} unknown.`;}
async function refreshAnalysis(){const requestId=++analysisRequestId,requestedOffset=analysisOffset;try{const response=await fetch(`/api/system/analysis-status?limit=${analysisLimit}&offset=${requestedOffset}`),data=await response.json();if(requestId!==analysisRequestId)return;if(!response.ok)throw Error(data.detail||'Unable to load saved calculation status');analysisOffset=data.offset;analysisDisplayedOffset=data.offset;renderAnalysis(data);}catch(error){if(requestId!==analysisRequestId)return;analysisOffset=analysisDisplayedOffset;byId('analysisStatus').textContent=error.message;byId('analysisPrevious').disabled=analysisDisplayedOffset===0;byId('analysisNext').disabled=true;}}
function closeVersionResults(){versionResultsRequestId++;versionGroupId=null;versionRepresentative=null;versionResultsOffset=0;versionResultsDisplayedOffset=0;byId('versionResultsPanel').classList.add('hidden');byId('versionResultRows').replaceChildren();byId('versionResultsPage').textContent='No results loaded';byId('versionResultsPrevious').disabled=true;byId('versionResultsNext').disabled=true;}
function renderVersions(data){byId('versionRows').replaceChildren();for(const item of data.items){const row=document.createElement('tr'),label=document.createElement('td'),statusCell=document.createElement('td'),status=document.createElement('span'),reason=document.createElement('div'),version=document.createElement('td'),schema=document.createElement('td'),settings=document.createElement('td'),count=document.createElement('td'),dates=document.createElement('td'),action=document.createElement('td'),button=document.createElement('button'),first=document.createElement('div'),latest=document.createElement('div');label.textContent=item.label;status.className='state '+item.state;status.textContent=item.state==='CURRENT'?'Current':item.state==='STALE'?'Stale':'Unknown';reason.textContent=item.reasons.join(' ');statusCell.append(status,reason);version.textContent=item.analysis_version;schema.textContent=item.payload_schema_version===null?'Unreadable':String(item.payload_schema_version);settings.append(detailIdentifier(item.settings_fingerprint,'Show settings fingerprint'));count.textContent=String(item.result_count);first.textContent=`First: ${dateText(item.earliest_generated_at)}`;latest.textContent=`Latest: ${dateText(item.latest_generated_at)}`;dates.append(first,latest);button.className='compact';button.dataset.analysisVersions='';button.textContent='View saved results';button.onclick=()=>openVersionResults(item);action.append(button);row.append(label,statusCell,version,schema,settings,count,dates,action);byId('versionRows').append(row);}const start=data.total_groups?data.offset+1:0,end=data.offset+data.items.length;byId('versionPage').textContent=data.total_groups?`Showing ${start}-${end} of ${data.total_groups} exact saved-version groups`:'No saved calculation versions yet.';byId('versionPrevious').disabled=data.offset===0;byId('versionNext').disabled=!data.has_more;byId('versionStatus').textContent=`This page: ${data.page_counts.CURRENT} current, ${data.page_counts.STALE} stale, ${data.page_counts.UNKNOWN} unknown groups. These are page counts, not database-wide totals.`;}
async function refreshVersions(){const requestId=++versionRequestId,requestedOffset=versionOffset;try{const response=await fetch(`/api/system/analysis-versions?limit=${versionLimit}&offset=${requestedOffset}`),data=await response.json();if(requestId!==versionRequestId)return;if(!response.ok)throw Error(data.detail||'Unable to load saved calculation versions');versionOffset=data.offset;versionDisplayedOffset=data.offset;renderVersions(data);}catch(error){if(requestId!==versionRequestId)return;versionOffset=versionDisplayedOffset;byId('versionStatus').textContent=error.message;byId('versionRows').replaceChildren();byId('versionPrevious').disabled=versionDisplayedOffset===0;byId('versionNext').disabled=true;}}
function renderVersionResults(data){byId('versionResultRows').replaceChildren();for(const item of data.items){const row=document.createElement('tr'),created=document.createElement('td'),identity=document.createElement('td'),action=document.createElement('td');created.textContent=dateText(item.generated_at);identity.append(detailIdentifier(item.result_id));if(data.state==='CURRENT'){const button=document.createElement('button');button.className='compact';button.dataset.analysisInputs='';button.textContent='Open result inputs';button.onclick=()=>openDependencies(item.result_id,data.label);action.append(button);}else{action.textContent='Input interpretation unavailable for this saved version';}row.append(created,identity,action);byId('versionResultRows').append(row);}const start=data.total?data.offset+1:0,end=data.offset+data.items.length;byId('versionResultsPage').textContent=data.total?`Showing ${start}-${end} of ${data.total} saved calculation results`:'No saved results remain in this group.';byId('versionResultsPrevious').disabled=data.offset===0;byId('versionResultsNext').disabled=!data.has_more;byId('versionResultsStatus').textContent=`${data.state==='CURRENT'?'Current':data.state==='STALE'?'Stale':'Unknown'} · ${data.reasons.join(' ')}`;}
async function refreshVersionResults(){const requestId=++versionResultsRequestId,groupId=versionGroupId,representative=versionRepresentative,requestedOffset=versionResultsOffset;try{const response=await fetch(`/api/system/analysis-versions/${encodeURIComponent(groupId)}/results?representative_result_id=${encodeURIComponent(representative)}&limit=${versionResultsLimit}&offset=${requestedOffset}`),data=await response.json();if(requestId!==versionResultsRequestId||groupId!==versionGroupId||representative!==versionRepresentative)return;if(!response.ok)throw Error(data.detail||'Unable to load results for this saved version');versionResultsOffset=data.offset;versionResultsDisplayedOffset=data.offset;renderVersionResults(data);}catch(error){if(requestId!==versionResultsRequestId||groupId!==versionGroupId||representative!==versionRepresentative)return;versionResultsOffset=versionResultsDisplayedOffset;byId('versionResultsStatus').textContent=error.message;byId('versionResultRows').replaceChildren();byId('versionResultsPrevious').disabled=true;byId('versionResultsNext').disabled=true;}}
function openVersionResults(item){closeDependencies();versionGroupId=item.group_id;versionRepresentative=item.representative_result_id;versionResultsOffset=0;versionResultsDisplayedOffset=0;byId('versionResultRows').replaceChildren();byId('versionResultsPage').textContent='Loading exact saved results';byId('versionResultsPrevious').disabled=true;byId('versionResultsNext').disabled=true;byId('versionResultsPanel').classList.remove('hidden');byId('versionResultsTitle').textContent=`Saved results · ${item.label} · ${item.analysis_version}`;byId('versionResultsStatus').textContent='Loading this exact saved-version group.';refreshVersionResults();byId('versionResultsPanel').scrollIntoView({behavior:'smooth',block:'start'});}
function closeSources(){sourceRequestId++;sourceRole=null;sourceOffset=0;sourceDisplayedOffset=0;byId('sourcePanel').classList.add('hidden');byId('sourceRows').replaceChildren();byId('sourcePage').textContent='No source records loaded';byId('sourcePrevious').disabled=true;byId('sourceNext').disabled=true;}
function closeImpact(){impactRequestId++;impactRole=null;impactOffset=0;impactDisplayedOffset=0;byId('impactPanel').classList.add('hidden');byId('impactRows').replaceChildren();byId('impactPage').textContent='No saved calculations loaded';byId('impactPrevious').disabled=true;byId('impactNext').disabled=true;}
function closeDependencies(){dependencyRequestId++;closeSources();closeImpact();dependencyResultId=null;byId('dependencyPanel').classList.add('hidden');byId('dependencyRows').replaceChildren();byId('dependencyPage').textContent='No inputs loaded';byId('dependencyPrevious').disabled=true;byId('dependencyNext').disabled=true;}
function renderDependencies(data){byId('dependencyRows').replaceChildren();for(const item of data.items){const row=document.createElement('tr'),role=document.createElement('td'),type=document.createElement('td'),meaning=document.createElement('td'),identity=document.createElement('td'),sources=document.createElement('td'),impact=document.createElement('td'),impactButton=document.createElement('button');role.textContent=roleLabel(item.role);type.textContent=item.type_label;meaning.textContent=item.explanation;identity.append(detailIdentifier(item.identity));if(item.source_records_supported){const count=document.createElement('div'),button=document.createElement('button');count.textContent=`${item.source_record_count} linked`;button.className='compact';button.dataset.analysisSources='';button.textContent='View source records';button.onclick=()=>openSources(item.role);sources.append(count,button);}else{sources.textContent='Descriptor only';}impactButton.className='compact';impactButton.dataset.analysisImpact='';impactButton.textContent='Show calculations using this input';impactButton.onclick=()=>openImpact(item.role);impact.append(impactButton);row.append(role,type,meaning,identity,sources,impact);byId('dependencyRows').append(row);}const start=data.total?data.offset+1:0,end=data.offset+data.items.length;byId('dependencyPage').textContent=data.total?`Showing ${start}-${end} of ${data.total} declared inputs`:'No declared inputs.';byId('dependencyPrevious').disabled=data.offset===0;byId('dependencyNext').disabled=!data.has_more;byId('dependencyStatus').textContent=`Verified saved input relationships for ${data.label}.`;}
async function refreshDependencies(){const requestId=++dependencyRequestId,resultId=dependencyResultId,requestedOffset=dependencyOffset;try{const response=await fetch(`/api/system/analysis-status/${encodeURIComponent(resultId)}/inputs?limit=${dependencyLimit}&offset=${requestedOffset}`),data=await response.json();if(requestId!==dependencyRequestId||resultId!==dependencyResultId)return;if(!response.ok)throw Error(data.detail||'Unable to load saved inputs');dependencyOffset=data.offset;dependencyDisplayedOffset=data.offset;renderDependencies(data);}catch(error){if(requestId!==dependencyRequestId||resultId!==dependencyResultId)return;dependencyOffset=dependencyDisplayedOffset;byId('dependencyStatus').textContent=error.message;byId('dependencyRows').replaceChildren();byId('dependencyPrevious').disabled=true;byId('dependencyNext').disabled=true;}}
function openDependencies(resultId,label){dependencyResultId=resultId;dependencyOffset=0;dependencyDisplayedOffset=0;closeSources();closeImpact();byId('dependencyRows').replaceChildren();byId('dependencyPage').textContent='Loading declared inputs';byId('dependencyPrevious').disabled=true;byId('dependencyNext').disabled=true;byId('dependencyPanel').classList.remove('hidden');byId('dependencyTitle').textContent=`Inputs and source records · ${label}`;byId('dependencyStatus').textContent='Loading verified input relationships.';refreshDependencies();byId('dependencyPanel').scrollIntoView({behavior:'smooth',block:'start'});}
function renderSources(data){byId('sourceRows').replaceChildren();for(const item of data.items){const row=document.createElement('tr'),recorded=document.createElement('td'),source=document.createElement('td'),filename=document.createElement('td'),actor=document.createElement('td'),size=document.createElement('td'),identity=document.createElement('td');recorded.textContent=new Date(item.observed_at).toLocaleString();source.textContent=`${item.source_kind} · ${item.source_ref}`;filename.textContent=item.original_filename||'Not recorded';actor.textContent=item.actor||'Not recorded';size.textContent=bytes(item.size_bytes);identity.append(detailIdentifier(item.observation_id));row.append(recorded,source,filename,actor,size,identity);byId('sourceRows').append(row);}const start=data.total?data.offset+1:0,end=data.offset+data.items.length;byId('sourcePage').textContent=data.total?`Showing ${start}-${end} of ${data.total} retained source records`:'No retained source record is linked to this input.';byId('sourcePrevious').disabled=data.offset===0;byId('sourceNext').disabled=!data.has_more;byId('sourceStatus').textContent=data.total?'Each row is a separate retained encounter with these exact registered bytes.':'The input remains recorded, but NCT does not reconstruct deleted provenance.';}
async function refreshSources(){const requestId=++sourceRequestId,resultId=dependencyResultId,role=sourceRole,requestedOffset=sourceOffset;try{const response=await fetch(`/api/system/analysis-status/${encodeURIComponent(resultId)}/inputs/${encodeURIComponent(role)}/source-records?limit=${sourceLimit}&offset=${requestedOffset}`),data=await response.json();if(requestId!==sourceRequestId||resultId!==dependencyResultId||role!==sourceRole)return;if(!response.ok)throw Error(data.detail||'Unable to load source records');sourceOffset=data.offset;sourceDisplayedOffset=data.offset;renderSources(data);}catch(error){if(requestId!==sourceRequestId||resultId!==dependencyResultId||role!==sourceRole)return;sourceOffset=sourceDisplayedOffset;byId('sourceStatus').textContent=error.message;byId('sourceRows').replaceChildren();byId('sourcePrevious').disabled=true;byId('sourceNext').disabled=true;}}
function openSources(role){closeImpact();sourceRole=role;sourceOffset=0;sourceDisplayedOffset=0;byId('sourceRows').replaceChildren();byId('sourcePage').textContent='Loading retained source records';byId('sourcePrevious').disabled=true;byId('sourceNext').disabled=true;byId('sourcePanel').classList.remove('hidden');byId('sourceTitle').textContent=`Source records · ${roleLabel(role)}`;byId('sourceStatus').textContent='Loading retained source records.';refreshSources();}
function renderImpact(data){byId('impactRows').replaceChildren();for(const item of data.items){const row=document.createElement('tr'),label=document.createElement('td'),relationship=document.createElement('td'),statusCell=document.createElement('td'),status=document.createElement('span'),reason=document.createElement('div'),created=document.createElement('td'),action=document.createElement('td');label.textContent=item.label;relationship.textContent=item.relationship_state==='VERIFIED'?`Verified direct role · ${roleLabel(item.role)}`:`Unsupported saved record · recorded role ${roleLabel(item.recorded_role)}`;status.className='state '+item.calculation_state;status.textContent=item.calculation_state==='CURRENT'?'Current':item.calculation_state==='STALE'?'Stale':'Unknown';reason.textContent=item.calculation_reasons.join(' ');statusCell.append(status,reason);created.textContent=new Date(item.generated_at).toLocaleString();if(item.relationship_state==='VERIFIED'){const button=document.createElement('button');button.className='compact';button.dataset.analysisInputs='';button.textContent='Open result inputs';button.onclick=()=>openDependencies(item.result_id,item.label);action.append(button);}else{action.textContent='Unavailable for this saved version';}row.append(label,relationship,statusCell,created,action);byId('impactRows').append(row);}const start=data.total_recorded_candidates?data.offset+1:0,end=data.offset+data.items.length;byId('impactPage').textContent=data.total_recorded_candidates?`Showing ${start}-${end} of ${data.total_recorded_candidates} recorded candidate relationships across ${data.calculation_count} saved calculations`:'No saved calculation records declare this exact typed input.';byId('impactPrevious').disabled=data.offset===0;byId('impactNext').disabled=!data.has_more;byId('impactStatus').textContent=`This page: ${data.page_verified_relationship_count} verified direct relationships and ${data.page_unsupported_candidate_count} unsupported saved-record candidates.`;}
async function refreshImpact(){const requestId=++impactRequestId,resultId=dependencyResultId,role=impactRole,requestedOffset=impactOffset;try{const response=await fetch(`/api/system/analysis-status/${encodeURIComponent(resultId)}/inputs/${encodeURIComponent(role)}/saved-calculations?limit=${impactLimit}&offset=${requestedOffset}`),data=await response.json();if(requestId!==impactRequestId||resultId!==dependencyResultId||role!==impactRole)return;if(!response.ok)throw Error(data.detail||'Unable to load saved calculations using this input');impactOffset=data.offset;impactDisplayedOffset=data.offset;renderImpact(data);}catch(error){if(requestId!==impactRequestId||resultId!==dependencyResultId||role!==impactRole)return;impactOffset=impactDisplayedOffset;byId('impactStatus').textContent=error.message;byId('impactRows').replaceChildren();byId('impactPrevious').disabled=true;byId('impactNext').disabled=true;}}
function openImpact(role){closeSources();impactRole=role;impactOffset=0;impactDisplayedOffset=0;byId('impactRows').replaceChildren();byId('impactPage').textContent='Loading saved calculation records';byId('impactPrevious').disabled=true;byId('impactNext').disabled=true;byId('impactPanel').classList.remove('hidden');byId('impactTitle').textContent=`Saved calculations using this input · ${roleLabel(role)}`;byId('impactStatus').textContent='Loading recorded direct relationships.';refreshImpact();}
async function start(mode){byId('inspect').disabled=true;byId('backfill').disabled=true;try{const response=await fetch('/api/system/storage/'+mode,{method:'POST'});const data=await response.json();if(!response.ok)throw Error(data.detail||'Unable to start storage operation');render(data);}catch(error){byId('status').textContent=error.message;byId('inspect').disabled=false;byId('backfill').disabled=false;}}
byId('inspect').onclick=()=>start('dry-run');byId('backfill').onclick=()=>start('backfill');byId('analysisPrevious').onclick=()=>{analysisOffset=Math.max(0,analysisDisplayedOffset-analysisLimit);refreshAnalysis();};byId('analysisNext').onclick=()=>{analysisOffset=analysisDisplayedOffset+analysisLimit;refreshAnalysis();};byId('versionPrevious').onclick=()=>{closeVersionResults();versionOffset=Math.max(0,versionDisplayedOffset-versionLimit);refreshVersions();};byId('versionNext').onclick=()=>{closeVersionResults();versionOffset=versionDisplayedOffset+versionLimit;refreshVersions();};byId('versionResultsPrevious').onclick=()=>{versionResultsOffset=Math.max(0,versionResultsDisplayedOffset-versionResultsLimit);refreshVersionResults();};byId('versionResultsNext').onclick=()=>{versionResultsOffset=versionResultsDisplayedOffset+versionResultsLimit;refreshVersionResults();};byId('dependencyPrevious').onclick=()=>{closeSources();closeImpact();dependencyOffset=Math.max(0,dependencyDisplayedOffset-dependencyLimit);refreshDependencies();};byId('dependencyNext').onclick=()=>{closeSources();closeImpact();dependencyOffset=dependencyDisplayedOffset+dependencyLimit;refreshDependencies();};byId('sourcePrevious').onclick=()=>{sourceOffset=Math.max(0,sourceDisplayedOffset-sourceLimit);refreshSources();};byId('sourceNext').onclick=()=>{sourceOffset=sourceDisplayedOffset+sourceLimit;refreshSources();};byId('impactPrevious').onclick=()=>{impactOffset=Math.max(0,impactDisplayedOffset-impactLimit);refreshImpact();};byId('impactNext').onclick=()=>{impactOffset=impactDisplayedOffset+impactLimit;refreshImpact();};byId('dependencyClose').onclick=closeDependencies;refresh();refreshAnalysis();refreshVersions();
</script></body></html>''')
